"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {
  Download,
  Terminal,
  BookOpen,
  Code2,
  Copy,
  Check,
} from "lucide-react";
import Link from "next/link";

const writeupTemplate = `# Penetration Test Report

**Target:** [Target IP/Domain]
**Date:** ${new Date().toLocaleDateString()}
**Author:** Anlen Jeban (an1en)
**Classification:** Confidential

---

## 1. Executive Summary

[Brief overview of the assessment, critical findings, and overall risk level]

**Risk Level:** [Critical / High / Medium / Low]
**Total Findings:** [X Critical, Y High, Z Medium]

---

## 2. Scope

| Item | Details |
|------|---------|
| Target | [IP/Domain] |
| Methodology | [Blackbox/Greybox/Whitebox] |
| Tools | Nmap, Burp Suite, [others] |

---

## 3. Methodology

### 3.1 Reconnaissance
\`\`\`
• Passive recon (OSINT)
• Subdomain enumeration
• Technology fingerprinting
\`\`\`

### 3.2 Scanning & Enumeration
\`\`\`bash
nmap -sV -sC -p- <target>
gobuster dir -u <url> -w /usr/share/wordlists/dirb/common.txt
\`\`\`

### 3.3 Exploitation
\`\`\`
• Vulnerability identification
• Exploit development / adaptation
• Initial foothold
\`\`\`

### 3.4 Privilege Escalation
\`\`\`
• Local enumeration (LinPEAS)
• SUID/SGID binary analysis
• Kernel exploit / misconfiguration
\`\`\`

---

## 4. Findings

### Finding 1: [Title]
**Severity:** [Critical/High/Medium/Low]
**Location:** [URL/Endpoint]
**CVSS Score:** [X.X]

**Description:**
[Detailed description of the vulnerability]

**Proof of Concept:**
\`\`\`bash
[Command or exploit code]
\`\`\`

**Impact:**
[What an attacker can achieve]

**Remediation:**
[How to fix]

---

## 5. Tools Used

| Tool | Purpose |
|------|---------|
| Nmap | Port scanning & service enumeration |
| Gobuster | Directory bruteforce |
| Burp Suite | Web traffic interception |
| [Tool] | [Purpose] |

---

## 6. Timeline

| Time | Event |
|------|-------|
| HH:MM | Started enumeration |
| HH:MM | Discovered [finding] |
| HH:MM | Gained initial access |
| HH:MM | Privilege escalation to root |

---

## 7. Recommendations

1. [Priority fix recommendation]
2. [Medium-term improvement]
3. [Long-term security enhancement]

---

*Report generated by SHADOW AI Assistant*
*© ${new Date().getFullYear()} Anlen Jeban*
`;

export default function WriteupPage() {
  const [content, setContent] = useState(writeupTemplate);
  const [copied, setCopied] = useState(false);
  const [title, setTitle] = useState("pentest-report");

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "-").toLowerCase()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen pt-20 px-4 pb-8">
      <div className="max-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass p-6 mb-6"
        >
          <div className="flex items-center gap-3 mb-4">
            <BookOpen className="text-[#00ff41]" size={28} />
            <div>
              <h1 className="text-2xl font-bold text-white">Report & Writeup Generator</h1>
              <p className="text-sm text-gray-500 font-mono">
                Create professional penetration testing reports and CTF writeups
              </p>
            </div>
          </div>

          <div className="flex flex-wrap gap-3">
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Report title..."
              className="hacker-input flex-1 min-w-[200px] text-sm"
            />
            <button onClick={handleCopy} className="hacker-btn text-sm flex items-center gap-2">
              {copied ? <Check size={16} /> : <Copy size={16} />}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button onClick={handleDownload} className="hacker-btn text-sm flex items-center gap-2">
              <Download size={16} />
              Download .md
            </button>
          </div>
        </motion.div>

        {/* Editor & Preview */}
        <div className="grid md:grid-cols-2 gap-6">
          {/* Editor */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="terminal-box"
          >
            <div className="flex items-center gap-2 px-4 py-2 text-xs text-gray-500 border-b border-[#00ff41]/20">
              <span className="w-3 h-3 rounded-full bg-[#ff0033]" />
              <span className="w-3 h-3 rounded-full bg-[#ffcc00]" />
              <span className="w-3 h-3 rounded-full bg-[#00ff41]" />
              <span className="ml-2">editor — report.md</span>
            </div>
            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              className="w-full h-[60vh] bg-transparent text-[#00ff41] font-mono text-sm p-4 outline-none resize-none border-none focus:ring-0"
              spellCheck={false}
            />
          </motion.div>

          {/* Preview */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="terminal-box"
          >
            <div className="flex items-center gap-2 px-4 py-2 text-xs text-gray-500 border-b border-[#00ff41]/20">
              <span className="w-3 h-3 rounded-full bg-[#00ff41]" />
              <span className="w-3 h-3 rounded-full bg-[#ffcc00]" />
              <span className="w-3 h-3 rounded-full bg-[#ff0033]" />
              <span className="ml-2">preview — rendered output</span>
            </div>
            <div className="h-[60vh] overflow-y-auto p-4 chat-markdown">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {content}
              </ReactMarkdown>
            </div>
          </motion.div>
        </div>

        {/* Tips */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mt-6 glass p-6"
        >
          <div className="flex items-center gap-3 mb-3">
            <Code2 size={18} className="text-[#00ff41]" />
            <h3 className="text-white font-bold font-mono text-sm">Pro Tips</h3>
          </div>
          <div className="grid md:grid-cols-3 gap-4 text-sm text-gray-400 font-mono">
            <div>
              <span className="text-[#00ff41]">[1]</span> Use hashtags for headers (# H1, ## H2)
            </div>
            <div>
              <span className="text-[#00ff41]">[2]</span> Wrap code in triple backticks ```code```
            </div>
            <div>
              <span className="text-[#00ff41]">[3]</span> Tables use pipe syntax | col1 | col2 |
            </div>
          </div>
        </motion.div>

        {/* Navigation */}
        <div className="mt-6 flex justify-center">
          <Link href="/chatbot" className="hacker-btn text-sm flex items-center gap-2">
            <Terminal size={16} />
            Generate with AI Assistant →
          </Link>
        </div>
      </div>
    </div>
  );
}
