import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { title, findings, target, author } = await req.json();

    if (!title || !findings) {
      return NextResponse.json(
        { error: "Title and findings are required" },
        { status: 400 }
      );
    }

    const report = generateReport({ title, findings, target, author });

    return NextResponse.json({ report });
  } catch (error) {
    console.error("Report generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate report" },
      { status: 500 }
    );
  }
}

function generateReport(data: {
  title: string;
  findings: string;
  target?: string;
  author?: string;
}) {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `# ${data.title}

**Target:** ${data.target || "N/A"}
**Date:** ${date}
**Author:** ${data.author || "Anlen Jeban (an1en)"}
**Classification:** Confidential

---

## Executive Summary

This report documents the findings from a security assessment.

**Risk Level:** TBD based on findings below

---

## Findings

${data.findings}

---

## Tools Used

- Nmap
- Burp Suite
- Custom scripts / exploits

---

## Recommendations

1. Address critical findings immediately
2. Implement security best practices
3. Regular security assessments

---

*Report generated by SHADOW AI Assistant*
*© ${new Date().getFullYear()} Anlen Jeban*
Generated on: ${date}`;
}
